// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kbpkdnptzvsvoujirfwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticGtkbnB0enZzdm91amlyZndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDc0NzgsImV4cCI6MjA4NTEyMzQ3OH0.Zhp7LnegfNmgMmrPitEoBRjr10SpsfjrGaWJAh2RAw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);